<?php

include_once 'lib/Inflector.php';
include_once 'helpers/PHPHelper.php';
include_once 'helpers/PHPDocHelper.php';

$fields = $source->getFields();
echo PHPHelper::OPEN . "\n";
echo PHPDocHelper::header(array('text' => 'Generated by phpIntern::controller on ' . date('Y-m-d'))) . "\n\n";
?>

include_once 'models/<?php echo Inflector::camelize($name); ?>.php';

class <?php echo Inflector::camelize(Inflector::pluralize($name)); ?>Controller extends ApplicationController {
	
	public function index ($coords) {
		list($this->items, $this->pager_html) = $this->paginate('<?php echo Inflector::camelize($name); ?>');
		$this->page['title'] = "Listing <?php echo Inflector::titleize(Inflector::pluralize($name)); ?>";
		$this->render();
	}
	
	public function add ($coords) {
		$this->errors = array();
		if (isset($_POST['submit'])) {
			$<?php echo $name; ?> = new <?php echo Inflector::camelize($name); ?>($_POST['<?php echo $name; ?>']);
			if ($<?php echo $name; ?>->save())
				$this->redirect('<?php echo Inflector::pluralize($name); ?>/index');
			else
				$this->errors = $<?php echo $name; ?>->getErrors();
		}

		$this->defaults = $_POST;
		$this->page['title'] = "Adding New <?php echo Inflector::titleize($name); ?>";
		$this->render(array('action' => 'form'));
	}
	
	public function edit ($coords) {
		$<?php echo $name; ?> = <?php echo Inflector::camelize($name); ?>Table()->get($coords['id']);

		if (isset($_POST['submit'])) {
			$<?php echo $name; ?>->merge($_POST['<?php echo $name; ?>']);
			
			if ($<?php echo $name; ?>->save()) {
				$this->redirect('<?php echo Inflector::pluralize($name); ?>/index');
			} else {
				$this->errors = $<?php echo $name; ?>->getErrors();
				$this->defaults = $_POST;
			}
		} else {
			$this->defaults['<?php echo $name; ?>'] = $<?php echo $name; ?>->toArray();
		}
		
		$this->page['title'] = "Editing <?php echo Inflector::titleize($name); ?>";
		$this->render(array('action' => 'form'));
	}
	
	public function delete ($coords) {
		<?php echo Inflector::camelize($name); ?>Table()->delete($coords['id']);
		$this->redirect('<?php echo Inflector::pluralize($name); ?>/index');
	}
	
}
<?php echo PHPHelper::CLOSE; ?>